name: CI Workflow (Backend)
on:
  workflow_call:
    inputs:
      has_fe_changes:
        required: true
        type: boolean
      has_be_changes:
        required: true
        type: boolean

jobs:
  python-lint:
    if: ${{ inputs.has_be_changes }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv venv
        working-directory: ${{ github.workspace }}/backend

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
        working-directory: ${{ github.workspace }}/backend

      - name: Analyze code with Pylint
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
          deactivate
        working-directory: ${{ github.workspace }}/backend