name: CI Workflow (Frontend)
on:
  workflow_call:
    inputs:
      has_fe_changes:
        required: true
        type: boolean
      has_be_changes:
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Typescript Linter
      run: echo "All valid 💪"