name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed_fe_files:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed_fe_files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed frontend files
        id: changed_fe_files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            **.ts
            **.tsx
            
  changed_be_files:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed_be_files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed backend files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            **.py
  
  be-ci:
    needs: [changed_fe_files, changed_be_files]
    uses: ./.github/workflows/ci-be.yml
    with:
      has_be_changes: ${{ needs.changed_be_files.outputs.any_changed == 'true' }}
      has_fe_changes: ${{ needs.changed_fe_files.outputs.any_changed == 'true' }}

  fe-ci:
    needs: [changed_fe_files, changed_be_files]
    uses: ./.github/workflows/ci-fe.yml
    with:
      has_be_changes: ${{ needs.changed_be_files.outputs.any_changed == 'true' }}
      has_fe_changes: ${{ needs.changed_fe_files.outputs.any_changed == 'true' }}

  sonarcloud:
    needs: [fe-ci, be-ci]
    timeout-minutes: 10
    name: Send a message so slack
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: $
          fetch-depth: 0
          
      - run: echo "CI worked 🚀"